---
- name: Remove old NTP servers on {{ inventory_hostname }}
  lineinfile:
    dest: /etc/ntp.conf
    regexp: "^server"
    state: absent

- name: Configure NTP servers on {{ inventory_hostname }}
  lineinfile:
    dest: /etc/ntp.conf
    line: "server {{ item }} iburst"
  with_items: "{{ ntp_server_list }}"

- name: Stop the ntpd service if running on {{ inventory_hostname }}
  service:
    name: ntpd
    state: stopped

- name: Manually sync time with ntp server on {{ inventory_hostname }}
  command: ntpdate -u "{{ntp_server_list[0]}}"

- name: Start ntpd on {{ inventory_hostname }} 
  service:
    name: ntpd
    state: started

- name: check ntp sync state
  shell: ntpstat | awk 'NR==1{print $1}'
  register: sync_status
  until: sync_status.stdout == "synchronised"
  retries: 29
  delay: 10