---
- name: upgrade all packages on {{ inventory_hostname }}
  yum:
    name: '*'
    state: latest

- name: install  packages
  yum: 
    name: "{{ item.pkgname }}"
    state: "present"
  with_items:
    - { pkgname: "epel-release"  }
    - { pkgname: "ntp" }

- name: Update /etc/hosts file on {{ inventory_hostname }}
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_host }} {{ inventory_hostname }}"

- name: Restart network service on {{ inventory_hostname }} 
  service:
    name: network
    state: restarted

- name: Start ntpd on {{ inventory_hostname }} 
  service:
    name: ntpd
    state: started

- name: check ntp sync state
  shell: ntpstat | awk 'NR==1{print $1}'
  register: sync_status
  until: sync_status.stdout == "synchronised"
  retries: 29
  delay: 10

- name: install  packages
  yum: 
    name: "{{ item.pkgname }}"
    state: "present"
  with_items:
    - { pkgname: "bridge-utils" }
    - { pkgname: "python3"}
    - { pkgname: "python34-setuptools"}
    - { pkgname: "golang" }
    - { pkgname: "git"}
    - { pkgname: "ansible"}

- name: install pip
  easy_install:
    name: pip
    state: latest

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_host }} {{item}}'
    state: present
  with_items: 
    - '{{ groups["bootstrap"] }}'
    - '{{ groups["master"] }}'
    - '{{ groups["node"] }}'
    
- name: install pip packages
  pip:
    name: "{{ item }}"
    #executable: pip3
    state: latest
  loop: 
    - docker