---
# - name: Download helm
#   get_url:
#     url: 'https://github.com/helm/helm/releases/tag/v2.14.3'
#     dest: '/usr/local/bin'
#     mode: 0755
#     use_proxy: yes

- name: download helm
  unarchive: 
    src: "{{ helm_url }}"
    dest: /tmp
    copy: no
  tags: download

- name: create the installation directory
  file:
    path: "{{ helm_bin_dir }}"
    state: directory

- name: copy helm binary
  copy:
    src: /tmp/linux-amd64/helm
    dest: "{{ helm_bin_dir }}"
    mode: 0755
    remote_src: yes