---
- name: create serviceaccount
  shell: kubectl create sa --namespace kube-system tiller
  register: result
  changed_when: "'created' in result.stdout"
  failed_when: "result.rc != 0 and 'already exists' not in result.stderr"

- name: create clusterrolebinding
  shell: kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
  register: result
  changed_when: "'created' in result.stdout"
  failed_when: "result.rc != 0 and 'already exists' not in result.stderr"

- name: "generate helm.json file"
  template:
      src: helm.yml.j2 
      dest: "{{ helm_bin_dir }}/helm.yml"
      mode: '0644'
  become: yes
  become_user: root
  become_method: sudo

- name: install tiller
  shell: kubectl apply -f {{ helm_bin_dir }}/helm.yml

# - name: install or upgrade tiller
#   shell: "{{ helm_bin_dir }}/helm init {{ helm_refresh_cache }} --upgrade"

- name: check serviceaccount field in {{ helm_tiller }} deployment
  shell: kubectl get deploy {{ helm_tiller }} -n kube-system -o yaml
  register: result
  changed_when: False

- name: update field of {{ helm_tiller }} deployment
  shell: kubectl patch deploy {{ helm_tiller }} -n kube-system -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
  register: result
  when: "'serviceAccount: tiller' not in result.stdout"