---
- hosts: master
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }
    
- hosts: node
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
#    - { role: cni, tags: cni }
    - { role: kubernetes/node, tags: node }


# - hosts: kube_cluster
#   gather_facts: yno
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - { role: calicoctl, tags: calicoctl }