---
- hosts: kube_cluster
  gather_facts: no
  serial: 1
  roles:
    - uc-centos-preconfig

- name: Setup docker 
  hosts: kube_cluster
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: docker, tags: docker }