---
- name: Setup Cluster underlay 
  hosts: kube_cluster
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
    #- { role: centos, tags: centos }
    #- { role: ntp, tags: ntp }
    #- { role: docker, tags: docker }
    #- { role: kubernetes/underlay, tags: underlay }
    #- { role: uc-centos-preconfig, tags: uc-centos-preconfig}
    - { role: ssh, tags: ssh }
    