---
- name: download istio
  unarchive: 
    src: "{{ istio_url }}"
    dest: /tmp
    copy: no
  tags: download

- name: create the installation directory
  file:
    path: "{{ istio_bin_dir }}"
    state: directory