---
- name: download istio
  unarchive: 
    src: "{{ istio_url }}"
    dest: /tmp
    copy: no
  tags: download

- name: create the installation directory
  file:
    path: "{{ istio_bin_dir }}"
    state: directory

# - name: copy helm binary
#   copy:
#     src: /tmp/linux-amd64/helm
#     dest: "{{ helm_bin_dir }}"
#     mode: 0755
#     remote_src: yes
#   become: yes
#   become_user: root
#   become_method: sudo