---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force --cri-socket /var/run/dockershim.sock"
  register: reset_cluster
  become: yes
  become_user: root
  become_method: sudo

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ master_ip }}:6443
  register: join_cluster
  become: yes
  become_user: root
  become_method: sudo
  notify:
    - Recreate kube-dns