- name: Copy file with owner and permissions
  copy:
    src: /Users/henderiw/.ssh/paco_rsa
    dest: ~/.ssh/paco_rsa
    owner: henderiw
    group: henderiw
    mode: 0600
  become_user: henderiw

- name: "generate ~/.ssh/config file"
  template:
      src: config.j2 
      dest: ~/.ssh/config 
      owner: henderiw 
      group: henderiw
      mode: '0600'
  loop: 
    - '{{ groups["all"] }}'
  become_user: henderiw
  