---
- name: Ensure directory exists for images
  file: 
    name: /home/{{ user }}/{{ image_dir }}/ 
    state: directory 
    mode: 0755
  become_user: "{{ user }}"

- name: Ensure directory exists for NRD
  file: 
    name: /home/{{ user }}/nrd/ 
    state: directory 
    mode: 0755
  become_user: "{{ user }}"

- name: NRD archiving
  block:
  - name: Find name of NRD Archive
    find: path="/home/{{ user }}/{{ image_dir }}/"  pattern="Nokia-NRD-Package-*"
    register: rc_nrd
  
  - name: Display rc_nrd
    debug:
      var: rc_nrd

  - name: Unpack NRD Archive
    unarchive: src="{{ rc_nrd.files[0].path}}" dest="/home/{{ user }}/nrd" list_files=yes remote_src=yes
    register: rc_nrd_archive_files
    when: rc_nrd.matched > 0

  - name: Display rc_nrd
    debug:
      var: rc_nrd_archive_files
  when: unpacked|default(false) 

- name: Ensure directory exists for CMM
  file: 
    name: /home/{{ user }}/cmm/ 
    state: directory 
    mode: 0755
  become_user: "{{ user }}"

- name: upload cmm.tar file to bootstrap vm
  copy:
    src: "{{ cmm_src_tar }}"
    dest: "/home/{{ user }}/cmm.tar"
    mode: 0644

- name: CMM archiving
  block:
  - name: Find name of CMM Archive
    find: path="/home/{{ user }}/"  pattern="cmm*"
    register: rc_cmm
  
  - name: Display rc_cmm
    debug:
      var: rc_cmm

  - name: Unpack NRD Archive
    unarchive: src="{{ rc_cmm.files[0].path}}" dest="/home/{{ user }}/cmm" list_files=yes remote_src=yes
    register: rc_cmm_archive_files
    when: rc_cmm.matched > 0

  - name: Display rc_cmm
    debug:
      var: rc_cmm_archive_files
  when: unpacked|default(false) 